### ISSUE TITLE
lets try to update to current rollup

### ISSUE THREAD

**Issue by frank-dspeed** [katrotz/rollup-plugin-less-modules#5]
This plugin needs a lot of upgrades in the tests and all over

**Comment by katrotz** [comment]
Upgraded dependencies and adjusted the plugin based on the Rollup v1.0.0 API changes.
To be noted that the plugin options slightly changed due to this:
- sourcemap option is now distinct from the rollup sourcemap option and should be provided via plugin option
- CSS bundle file path now takes into account also the `InputOptions#dir` rollup option (multi chunk use case)
